### ISSUE TITLE
Windows 10 LTSC 21H2 Support

### ISSUE THREAD

**Issue by Degl1** [lixuy/LTSC-Add-MicrosoftStore#31]
Mind updating this package as I am having trouble doing it myself. As it just gives errors upon installing it on 21H2 LTSC.

**Comment by dudefoxlive** [comment]
Strange this repo works just fine on my fresh 21H2 LTSC installation. I did notice some errors but I think they were saying that I was attempting to install an older version on top of a newer version.

**Comment by Degl1** [comment]
It just straight up didn't install so I found a new add Store to LSTC.

**Comment by doktornotor** [comment]
You do not need this at all for LTSC 2021. Just run

`wsreset -i `

as admin. (Twice if it doesn't work for the first time.)

**Comment by Degl1** [comment]
Yeah I found that command too myself 2 months ago but yeah for anyone else `wsreset -i` is the best.

**Comment by lawleagle** [comment]
`wsreset -i` worked for me too,, and indeed had to run it twice
is there any reason to keep this issue open?

**Comment by Hxd097** [comment]
> You do not need this at all for LTSC 2021. Just run
> 
> `wsreset -i `
> 
> as admin. (Twice if it doesn't work for the first time.)

Worked for me , amazing solution man

**Comment by dudefoxlive** [comment]
> `wsreset -i` worked for me too,, and indeed had to run it twice is there any reason to keep this issue open?

I don't think so.

**Comment by iamrusskih** [comment]
> wsreset -i

also worked for me, just want to ask,  maybe pin this issue? I spent a whole evening to understand how to make it works
